/**
 * Smooth curves through a series of points.
 *
 * A polyline through six consumption results looks like a saw; a smooth curve
 * reads as a trend, which is what the sparkline is actually for. Pure and
 * dependency-free — no charting library is pulled in for one line.
 */

export interface Point {
  x: number;
  y: number;
}

/**
 * A cubic Bézier path through every point, Catmull–Rom style.
 *
 * Control points are placed a sixth of the way along the vector between a
 * point's neighbours, which is the standard Catmull–Rom → Bézier conversion.
 * The ends reuse their own point as the missing neighbour so the curve starts
 * and finishes flat rather than flicking off.
 *
 * Control-point Y is clamped to the span of the segment it belongs to. Without
 * that, a flat run followed by a jump makes the curve dip below the lowest bar
 * on its way up — a wiggle the data does not contain, and on a fuel-economy
 * chart a wiggle reads as a month that never happened.
 */
export function smoothPath(points: readonly Point[], tension = 1): string {
  if (points.length === 0) return "";
  if (points.length === 1) return `M ${round(points[0].x)} ${round(points[0].y)}`;

  const at = (index: number): Point =>
    points[Math.min(points.length - 1, Math.max(0, index))];

  let path = `M ${round(points[0].x)} ${round(points[0].y)}`;

  for (let i = 0; i < points.length - 1; i += 1) {
    const previous = at(i - 1);
    const start = at(i);
    const end = at(i + 1);
    const next = at(i + 2);

    const low = Math.min(start.y, end.y);
    const high = Math.max(start.y, end.y);

    const c1 = {
      x: start.x + ((end.x - previous.x) / 6) * tension,
      y: clamp(start.y + ((end.y - previous.y) / 6) * tension, low, high),
    };
    const c2 = {
      x: end.x - ((next.x - start.x) / 6) * tension,
      y: clamp(end.y - ((next.y - start.y) / 6) * tension, low, high),
    };

    path += ` C ${round(c1.x)} ${round(c1.y)}, ${round(c2.x)} ${round(c2.y)}, ${round(end.x)} ${round(end.y)}`;
  }

  return path;
}

function clamp(value: number, low: number, high: number): number {
  return Math.min(high, Math.max(low, value));
}

/** Trim float noise so the emitted path stays short and stable between renders. */
function round(value: number): number {
  return Math.round(value * 100) / 100;
}

/**
 * Map a series onto a 0–1 scale.
 *
 * A flat run of near-identical results is returned at a constant mid height
 * rather than being stretched to fill the box: amplifying noise into a dramatic
 * shape is the most common way a sparkline lies.
 */
export function normalise(values: readonly number[], flatValue = 0.55): number[] {
  if (values.length === 0) return [];
  const min = Math.min(...values);
  const max = Math.max(...values);
  const span = max - min;
  if (!(span > 0)) return values.map(() => flatValue);
  return values.map((value) => (value - min) / span);
}

/** A point on a circle, with 0° at 3 o'clock and degrees rising anticlockwise. */
export function polar(cx: number, cy: number, radius: number, degrees: number): Point {
  const radians = (degrees * Math.PI) / 180;
  return { x: cx + radius * Math.cos(radians), y: cy - radius * Math.sin(radians) };
}

/**
 * An SVG arc path between two angles, drawn the short way round.
 *
 * Used for the dial's track and its filled portion, so both are generated by
 * the same function and cannot drift apart.
 */
export function arcPath(
  cx: number,
  cy: number,
  radius: number,
  fromDegrees: number,
  toDegrees: number,
): string {
  const start = polar(cx, cy, radius, fromDegrees);
  const end = polar(cx, cy, radius, toDegrees);
  const sweep = Math.abs(fromDegrees - toDegrees);
  const largeArc = sweep > 180 ? 1 : 0;
  // Angles fall as the dial fills, so the path is always drawn clockwise.
  return `M ${round(start.x)} ${round(start.y)} A ${radius} ${radius} 0 ${largeArc} 1 ${round(end.x)} ${round(end.y)}`;
}
