import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { canReadZip, listSheetNames, readWorkbook } from "./xlsx";
import { parseRows } from "./rows";

/**
 * XLSX reader compatibility.
 *
 * The reader is hand-written on the platform's DecompressionStream, so "it
 * works on the one file we have" is not evidence. These fixtures encode the
 * ways Excel and Google Sheets structurally differ, plus the cell shapes that
 * historically break naive parsers. Each is generated by
 * scripts/makeXlsxFixtures.mjs from invented data.
 */

const DIR = new URL("./__fixtures__/", import.meta.url);

function load(name: string): ArrayBuffer {
  const buffer = readFileSync(new URL(name, DIR));
  return buffer.buffer.slice(
    buffer.byteOffset,
    buffer.byteOffset + buffer.byteLength,
  ) as ArrayBuffer;
}

describe("runtime capability", () => {
  it("detects whether this runtime can inflate", () => {
    // Node 18+ and every browser the app targets. The import screen checks
    // this and tells the user to export CSV instead when it is false, rather
    // than failing opaquely.
    expect(canReadZip()).toBe(true);
    expect(typeof DecompressionStream).toBe("function");
  });
});

/* ------------------------------------------------------------------ *
 * Excel-shaped: shared strings, styled date serials, omitted empties
 * ------------------------------------------------------------------ */

describe("an Excel-generated workbook", () => {
  const file = () => load("xlsx-excel-shared-strings.xlsx");

  it("resolves shared strings, including Hebrew and a non-breaking space", async () => {
    const sheet = await readWorkbook(file());
    expect(sheet.name).toBe("Fuel Data");
    expect(sheet.rows[0][0]).toBe("תאריך");
    expect(sheet.rows[0][2]).toBe("קילומטראז'");
    // "פז חגור" joined by U+00A0, which must survive to the normaliser.
    expect(String(sheet.rows[1][6])).toContain("פז");
  });

  it("converts a styled numeric date serial into a real date", async () => {
    const sheet = await readWorkbook(file());
    const cell = sheet.rows[1][0];
    expect(cell).toBeInstanceOf(Date);
    expect((cell as Date).getFullYear()).toBe(2026);
    expect((cell as Date).getMonth()).toBe(0);
    expect((cell as Date).getDate()).toBe(5);
  });

  it("leaves an unstyled number as a number, not a date", async () => {
    const sheet = await readWorkbook(file());
    expect(sheet.rows[1][2]).toBe(100_000);
    expect(sheet.rows[1][3]).toBe(31.5);
  });

  it("reads a styled time fraction as a clock time", async () => {
    const result = parseRows(await rowsOf(file()));
    const when = new Date(result.rows[1].date);
    expect(when.getHours()).toBe(18);
    expect(when.getMinutes()).toBe(47);
  });

  it("handles cells Excel omits entirely when empty", async () => {
    const sheet = await readWorkbook(file());
    // Row 4 has no station and no note; the cells are absent from the XML.
    const row = sheet.rows[3];
    expect(row[6] ?? null).toBeNull();
    expect(row[7] ?? null).toBeNull();
  });

  it("imports every row", async () => {
    const result = parseRows(await rowsOf(file()));
    expect(result.rejected).toHaveLength(0);
    expect(result.rows).toHaveLength(3);
    expect(result.rows[0].odometer).toBe(100_000);
    expect(result.rows[0].totalCost).toBeCloseTo(236.25, 2);
  });
});

/* ------------------------------------------------------------------ *
 * Google-Sheets-shaped: inline strings, text dates, no styles part
 * ------------------------------------------------------------------ */

describe("a Google-Sheets-generated workbook", () => {
  const file = () => load("xlsx-sheets-inline-strings.xlsx");

  it("reads inline strings with no sharedStrings part present", async () => {
    const sheet = await readWorkbook(file());
    expect(sheet.rows[0][0]).toBe("תאריך");
    expect(String(sheet.rows[1][6])).toContain("פז חגור");
  });

  it("normalises bidi marks, NBSP, currency and units out of the values", async () => {
    const result = parseRows(await rowsOf(file()));
    expect(result.rejected).toHaveLength(0);

    // "100,000 ק\"מ" with a non-breaking space.
    expect(result.rows[0].odometer).toBe(100_000);
    // A DECIMAL comma: "31,5".
    expect(result.rows[0].liters).toBeCloseTo(31.5, 3);
    // RLM + narrow NBSP + shekel sign around the amount.
    expect(result.rows[0].totalCost).toBeCloseTo(236.25, 2);
  });

  it("accepts both date spellings in the same file", async () => {
    const result = parseRows(await rowsOf(file()));
    const first = new Date(result.rows[0].date); // 05/01/2026
    const second = new Date(result.rows[1].date); // 2026-01-19
    expect(first.getMonth()).toBe(0);
    expect(first.getDate()).toBe(5);
    expect(second.getDate()).toBe(19);
    expect(second.getHours()).toBe(18);
    expect(second.getMinutes()).toBe(47);
  });

  it("treats a hyphen placeholder as empty rather than as a value", async () => {
    const result = parseRows(await rowsOf(file()));
    expect(result.rows[1].station).toBeNull();
    expect(result.rows[1].notes).toBeNull();
  });

  it("skips a row of nothing but empty cells without rejecting it", async () => {
    const result = parseRows(await rowsOf(file()));
    expect(result.rows).toHaveLength(2);
    expect(result.rejected).toHaveLength(0);
  });
});

/* ------------------------------------------------------------------ *
 * Multiple worksheets
 * ------------------------------------------------------------------ */

describe("a workbook with several sheets", () => {
  const file = () => load("xlsx-multi-sheet.xlsx");

  it("lists every sheet name", async () => {
    expect(await listSheetNames(file())).toEqual(["Notes", "Fuel Data"]);
  });

  it("can be pointed at a sheet other than the first", async () => {
    const sheet = await readWorkbook(file(), "Fuel Data");
    expect(sheet.name).toBe("Fuel Data");
    const result = parseRows(sheet.rows);
    expect(result.rows).toHaveLength(1);
    expect(result.rows[0].odometer).toBe(200_000);
    expect(result.rows[0].fuelType).toBe("diesel");
  });

  it("defaults to the first sheet, which here has no importable data", async () => {
    const sheet = await readWorkbook(file());
    expect(sheet.name).toBe("Notes");
    const result = parseRows(sheet.rows);
    // Reported as unrecognisable rather than silently importing nothing.
    expect(result.rows).toHaveLength(0);
    expect(result.rejected[0].reason).toContain("שורת כותרות");
  });
});

/* ------------------------------------------------------------------ *
 * Formulas
 * ------------------------------------------------------------------ */

describe("a workbook whose raw inputs are formulas", () => {
  const file = () => load("xlsx-formulas.xlsx");

  it("reads the cached value but records that it was computed", async () => {
    const sheet = await readWorkbook(file());
    // Row 2: total is =D2*7.5 with a cached 300.
    expect(sheet.rows[1][4]).toBe(300);
    expect(sheet.formulas[1][4]).toBe(true);
    // The plain neighbour is not flagged.
    expect(sheet.formulas[1][3]).toBe(false);
  });

  it("imports the row and warns that the value was not typed", async () => {
    const sheet = await readWorkbook(file());
    const result = parseRows(sheet.rows, sheet.formulas);

    expect(result.rows.length).toBeGreaterThan(0);
    expect(result.warnings.join(" ")).toContain("חושבו בנוסחה");
    expect(result.warnings.join(" ")).toContain("מחיר כולל");
  });

  it("flags a formula-derived odometer, which is a raw input the user never typed", async () => {
    const sheet = await readWorkbook(file());
    const result = parseRows(sheet.rows, sheet.formulas);
    expect(result.warnings.join(" ")).toContain("קילומטראז׳");
  });

  it("rejects a row whose formula evaluated to an error", async () => {
    const sheet = await readWorkbook(file());
    const result = parseRows(sheet.rows, sheet.formulas);
    // #DIV/0! in the litres column: there is no usable value, so the row is
    // reported rather than imported with a guess.
    expect(result.rejected.some((entry) => entry.reason.includes("כמות דלק"))).toBe(true);
  });

  it("does not flag anything when no formula information is supplied", async () => {
    const sheet = await readWorkbook(file());
    const result = parseRows(sheet.rows);
    expect(result.warnings.join(" ")).not.toContain("חושבו בנוסחה");
  });
});

async function rowsOf(file: ArrayBuffer): Promise<unknown[][]> {
  return (await readWorkbook(file)).rows;
}
